Repository Social-Media-Public-Analysis/Social-Media-Public-Analysis, pull requests merged in 2020-09, with the labels that each got.

#22 Some refactoring
  .github/workflows/python-app.yml
  Dozent/DownloaderTools.py
  Dozent/__init__.py
  Dozent/dozent.py
  README.md
  sentiment_analysis_app.py
  sentiment_analysis_tools/__init__.py
  sentiment_analysis_tools/sentiments.py
Labels: CLI, documentation, enhancement

#23 Creating unit tests
  .github/workflows/python-app.yml
  README.md
  dozent/__init__.py
  dozent/downloader_tools.py
  dozent/dozent.py
  preprocess/__init__.py
  preprocess/preprocess.py
  sentiment_analysis_tools/__init__.py
  sentiment_analysis_tools/sentiments.py
  tests/__init__.py
  tests/test_downloader_tools.py
  tests/test_sentiments.py
Labels: CLI, documentation, enhancement

#39 Adding Morpheus to the Master Branch
  Morpheus/__init__.py
  Morpheus/batch_processing.py
  Morpheus/classification/__init__.py
  Morpheus/classification/sentiments.py
  Morpheus/data_loading.py
  Morpheus/filters.py
  data/test_sample_files.json.bz2
  data/test_sample_files_2.json.bz2
  examples/Morpheus/__init__.py
  examples/Morpheus/batch_processing/__init__.py
  examples/Morpheus/batch_processing/batch_processing_counting_tweets.py
  examples/__init__.py
  requirements.txt
  sentiment_analysis_app.py
  tests/test_sentiments.py
Labels: documentation, morpheus

#41 Adding tests
  .github/workflows/python-app.yml
  dozent/dozent.py
  dozent/twitter-archive-stream-links.json
  examples/Morpheus/batch_processing/batch_processing_counting_tweets.py
  morpheus/data_loading.py
  morpheus/filters.py
  sentiment_analysis_app.py
  tests/__init__.py
  tests/dozent/__init__.py
  tests/dozent/test_downloader_tools.py
  tests/morpheus/__init__.py
  tests/morpheus/classification/__init__.py
  tests/morpheus/classification/test_sentiments.py
  tests/morpheus/test_data_loading.py
  tests/morpheus/test_filters.py
Labels: documentation, enhancement, morpheus

#51 Update python-app.yml
  .github/workflows/python-app.yml
Labels: documentation, enhancement, overall
